DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users(
    user_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS game2users CASCADE;
CREATE TABLE game2users(
user_id SERIAL FOREIGN KEY,
game_id SERIAL FOREIGN KEY,
);
